{"name": "test_login[invalid_user-wrong_password-False]", "status": "broken", "statusDetails": {"message": "_pytest.fixtures.FixtureLookupError: ('self', <FixtureRequest for <Function test_login[invalid_user-wrong_password-False]>>)", "trace": "file /Users/unais/PycharmProjects/EcommercePageObjectModelFramework/TestCases/test_login.py, line 9\n  @pytest.mark.parametrize(\"username,password,expected\", [\n      (\"standard_user\", \"secret_sauce\", True),        # Valid credentials\n      (\"locked_out_user\", \"secret_sauce\", False),    # Locked-out user\n      (\"invalid_user\", \"wrong_password\", False)      # Invalid credentials\n  ])\n  def test_login(self, username, password, expected, browser):\nE       fixture 'self' not found\n>       available fixtures: browser, cache, capfd, capfdbinary, caplog, capsys, capsysbinary, doctest_namespace, login, monkeypatch, pytestconfig, record_property, record_testsuite_property, record_xml_attribute, recwarn, setup_teardown, tmp_path, tmp_path_factory, tmpdir, tmpdir_factory\n>       use 'pytest --fixtures [testpath]' for help on them.\n\n/Users/unais/PycharmProjects/EcommercePageObjectModelFramework/TestCases/test_login.py:9"}, "parameters": [{"name": "username", "value": "'invalid_user'"}, {"name": "password", "value": "'wrong_password'"}, {"name": "expected", "value": "False"}], "start": 1726738436758, "stop": 1726738436758, "uuid": "a154db7c-3923-4732-96d9-efe8c83f4661", "historyId": "fb6ea5cbcbc4e4a5b86d013e70523390", "testCaseId": "96bea9459c71e2d0f628fa02f717d424", "fullName": "TestCases.test_login#test_login", "labels": [{"name": "parentSuite", "value": "TestCases"}, {"name": "suite", "value": "test_login"}, {"name": "host", "value": "unaiss-MacBook-Air.local"}, {"name": "thread", "value": "80560-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "TestCases.test_login"}]}